### ISSUE TITLE
EPIC 3.1: As a system Administrator I want to be able to perform CRUD operations on all Vehicles, so I can manage the catalog display information 

### ISSUE THREAD

**Issue by OGHO-SAYE** [samjamhen/Watermelons-soen341projectW2024#120]
## USER ACCEPTANCE FLOW

- System administrator can access Vehicle management
- System administrator can perform CRUD operations on selected Vehicle(s)
    - CREATE
    - READ
    - UPDATE
    - DELETE
    
## ACCEPTANCE CRITERIA

-  #11 
-  #55
-  #56 
-  #57

**Comment by samjamhen** [comment]
Epic successfully completed. All US closed
