### ISSUE TITLE
Epic 2.1 As a Customer, I shall be able to check-in to take my reserved vehicle.

### ISSUE THREAD

**Issue by 7anine** [samjamhen/Watermelons-soen341projectW2024#175]
Acceptance Criteria:

Users can reserve a rental car through the system.
The designated pick-up location is prepared and staffed for user arrivals.
Users can collect the rented car at the scheduled date and time by presenting required documents.
Users can inspect the rented car for damages and report them if necessary.
Users can sign the rental agreement electronically or physically.
The status of the rented vehicle is updated in the system after the rental agreement is signed.
A deposit of 500 CAD is requested from the bank entity, and users can drive away with the rented car upon successful deposit processing.

#173 
#174
#275

**Comment by samjamhen** [comment]
Epic successfully completed. All US closed
