### ISSUE TITLE
Epic 1.2: As a customer, I want to be able to start a reservation so that I can rent a vehicle for my desired location and time period

### ISSUE THREAD

**Issue by 7anine** [samjamhen/Watermelons-soen341projectW2024#22]
User Acceptance Flow:

1. As a customer, I should be able to input my location using either a postal code, city name, or airport code.
2. I should be able to specify the pickup and return dates for my reservation.
3. Upon providing the location and dates, the system should display a list of available vehicles that match my criteria.
4. The displayed vehicles should include options for different types (e.g., CARs, SUVs, Vans, Trucks), categories (e.g., compact, standard, intermediate), and price ranges.
5. I should have the option to add extra equipment to my reservation, with additional charges clearly displayed.
6. The system should provide a clear and intuitive interface for starting the reservation process and selecting additional equipment.
7. Once I have completed the reservation, I should receive confirmation of my booking along with details of the selected vehicle and any added equipment.

Acceptance Criteria:
- User Acceptance Flow is respected 
- [x] #23 
- [x] #24 
- [x] #25 
- [x] #26 
- [x] #27

**Comment by samjamhen** [comment]
Epic successfully completed. All US closed
