### ISSUE TITLE
US 1.2.2 As a customer, I want to see available fetch vehicles that correspond to the criteria I gave in my reservation form

### ISSUE THREAD

**Issue by 7anine** [samjamhen/Watermelons-soen341projectW2024#24]
User Story Description
As a user filling out a reservation form, I want to view available vehicles based on the pickup and return date, as well as the location I specify, ensuring that the displayed vehicles match my criteria.

User Acceptance Flow:

User selects the submit button on the reservation form
System dynamically fetches available vehicles based on the specified pickup and return dates and location.
System displays the list of available vehicles matching the user's criteria within the reservation form.

Acceptance Criteria:
Upon selecting dates and entering the pickup location, the system should fetch and display available vehicles without the need for page refresh.
The displayed vehicles should include relevant details such as make, model, and price.
If no vehicles match the specified criteria, a message indicating the unavailability of vehicles should be displayed within the reservation form.
The displayed vehicles should only include those that are available for the specified pickup and return dates and match the location entered by the user.

- #93
- #94

**Comment by OGHO-SAYE** [comment]
Read operation completed
