### ISSUE TITLE
Task 4.1.1: Design and implement page for listing car rental requests on the customer interface.

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#298]
## Task Description
As a developer, I want to implement a page for customers to view their requests or/and make a request to list their car for rent.

## Acceptance Criteria:

- [ ] The page display a button to create a new request
- [ ] The page display customer's request(s) and their status

**Comment by OGHO-SAYE** [comment]
This has been completed, and is present in the customer home page
