### ISSUE TITLE
Task 4.1.4: Backend functionality to save the request in the database

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#301]
## Task Description: 
As a developer, I want to create a database to save the requests made by customers. When a customer submit a request, the request should be saved to the database and its status should be set to "In Progress".

## Acceptance Criteria:

- [x] Request is successfully saved in database after submitting the form

**Comment by samjamhen** [comment]
Task successfully completed. Status saved to "pending."
