### ISSUE TITLE
Task 4.3.2: Display requests made by customers and saved in the database

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#304]
## Task Description:
As a developer, I want to display the request made by customers on the request management page. The requests are saved on the database and displayed on the admin side.

## Acceptance Criteria:

- [x] Requests saved on the database are successfully displayed on the admin side

**Comment by OGHO-SAYE** [comment]
This has been completed, and is functional
