### ISSUE TITLE
Task 4.3.3: Display all the listing details when selecting a request

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#305]
## Task Description:
As a developer, I want to display all details of a request when a system administrator select a specific request. An option "Show more" should be displayed to the system administrator to display all information requested by customer. 

## Acceptance Criteria: 

- [ ] Details are displayed successfully

**Comment by OGHO-SAYE** [comment]
This has been implemented, and SA, has a display list of all active applications
