### ISSUE TITLE
Task 4.4.2: Send email to alert customer of the request decision

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#307]
## Task Description: 
As a developer, I want to send an email to notify the customer of the request decision. If system administrator select "Approve", customer receives an email saying that his request has been approved and his car has been added to the catalog. Otherwise, he receives an email with the reason why his request has been declined.

## Acceptance Criteria:

- [x] Email is successfully send

**Comment by samjamhen** [comment]
Task successfully completed, user notified by email when vehicle is approved.
