### ISSUE TITLE
Task 4.4.3: Update status of a request by system administrator

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#308]
## Task Description
As a developer, I want to update the status of a request on the database after selecting "approve" or "decline" button. The status should be set from "in Progress" to the according decision made by a system administrator. 

## Acceptance Criteria

- [ ] Request status is successfully updated

**Comment by OGHO-SAYE** [comment]
This has been implemented successfully, rejected, and approved situations are updated.
