### ISSUE TITLE
Task 4.4.4: Add vehicle to the catalog if request is approved

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#309]
## Task Description: 
As a developer, I want to add the vehicle on the request made by a customer on the catalog if approved. Once the system administrator approves the request, the vehicle should be listed on the catalog and available for rent.

## Acceptance Criteria: 

- [ ] Vehicle is displayed successfully on the catalog after being approved.

**Comment by OGHO-SAYE** [comment]
This has been completed, and is functional in our program
