### ISSUE TITLE
EPIC 3.2: As a system administrator, I want to perform CRUD (CREATE, READ, UPDATE, DELETE) so that I can manage users within the system.

### ISSUE THREAD

**Issue by bxnjiho** [samjamhen/Watermelons-soen341projectW2024#86]
## User Acceptance Flow
- System administrator can access user management
- System administrator is able to perform CRUD operations on selected user(s)
    - CREATE
    - READ
    - UPDATE
    - DELETE
## Acceptance Criteria
- #2 
- #51 
- #77 
- #78

**Comment by samjamhen** [comment]
Epic successfully completed. All US closed
